config/routes.rb
BonTime::Application.routes.draw do
  root "homes#index"

  resources :messages, only: [:new, :create]

  resources :friendships, only: [:create] do
    member do
      post :accept_invitation
      post :decline_invitation
      post :revoke
    end
  end

  resources :locations

  resources :events do
    match '/events/new', to: 'events#create', via: :post
    resources :attendances do
      member do
        post :send_invite
        post :decline_invite
      end
    end
  end
  
  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do 
    resources :users, only: [:index, :show, :edit] do
    match '/users/sign_up', to: 'registrations#new', via: :post
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events, through: :attendances
  has_many :attendances, foreign_key: "attendee_id"
  
  has_many :created_events, class_name: "Event", foreign_key: "creator_id"

  has_many :locations, as: :addressable
  accepts_nested_attributes_for :locations
  
  validates :first_name, presence: true
  
  include ActsAsFriendable

  

  def name
    "#{first_name} #{last_name}"
  end

  def json_locations
    locations = self.locations.map { |l| { id: l.id, lat: l.latitude, long: l.latitude } }
    locations.to_json
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_filter :authenticate_user!

  def index
    if user_signed_in?
      @users = User.all
      @friends = current_user.friends
    else
      redirect_to new_user_session_path, notice: "You need to sign in or sign up before continuing."
    end
  end



  def show
    if user_signed_in?
      @user = User.find params[:id]
      @location = current_user.locations.new
      # @invites = @user.pending_friendships.includes(:user)
      @friends = current_user.friends
    else
      redirect_to new_user_session_path, notice: "You need to sign in or sign up before continuing."
    end
  end

  def update
  end

end

app/helpers/users_helper.rb
module UsersHelper


  # client.account.sms.messages.create(body: "You should leave in 10 min", to: "current_user.mobile", from: ENV["TWILIO_NUM"])
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

app/views/users/index.html.haml
- if current_user.requested_friendships.any?
  %h2 Pending Friendship Requests
  %table
    %thead
      %tr
        %th Name
        %th Email
        %th
    %tbody
      - current_user.requested_friendships.each do |request|
        %tr
          %td= request.first_name.capitalize
          %td= request.email
          %td= link_to "Accept", accept_invitation_friendship_path(request), method: :post, class: "btn btn-primary"
          %td= link_to "Decline", decline_invitation_friendship_path(request), method: :post, class: "btn btn-primary"
%br/

%h2 Friends
%table
  %thead
    %tr
      %th First name
      %th Last name
      %th
  %tbody
    - if current_user.friends.any?
      - current_user.friends.each do |friend|
        %tr
          %td= friend.first_name.capitalize
          %td= friend.last_name.capitalize
          %td
    - else
      %tr
        %td You need to add some friends!
%br/


%h2 Other Users
%table
  %thead
    %tr
      %th First name
      %th Last name
      %th Email
      %th
  %tbody
    - @users.each do |user|
      %tr
        - unless user == current_user
          / - unless current_user.friends.include?(user)
          /   - unless current_user.requested_friendships.include?(user)
          %td= user.first_name.capitalize
          %td= user.last_name.capitalize
          %td= user.email
          %td
            - unless current_user.requested_friendships.include?(user) || current_user.friends.include?(user)
              = form_for user.inverse_friendships.build, url: friendships_path do |f|
                = f.hidden_field :friend_id
                = f.submit "Add Friend", class: "btn btn-primary"

- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/users/new.html.haml
%h1 New Address

= render 'form'

= link_to 'Back', event_path

app/views/users/show.html.haml
%h2= current_user.name
%h3 Number
- if current_user.mobile_number.present?
  %p= current_user.mobile_number
- else
  %p This user hasn't added a mobile number.

%h3 Email
%p= current_user.email
%br

- if @user == current_user
  = link_to 'Update info', edit_user_path

  %h3 My addresses
  %table
    %tbody
    - current_user.locations.each do |loc|
      %tr
        %th
          %b= loc.location_label
      %tr
        %td= loc.full_address

  %br
  %h3 Add Or Edit Address
  = render partial: "locations/form"
  %br

app/views/users/update.html.haml
%h1 Update Addresses

= render 'form'

= link_to 'Back', event_path