config/routes.rb
BonTime::Application.routes.draw do
  root "homes#index"

  resources :messages, only: [:new, :create]

  resources :friendships, only: [:create] do
    member do
      post :accept_invitation
      post :decline_invitation
      post :revoke
    end
  end

  resources :locations

  resources :events do
    match '/events/new', to: 'events#create', via: :post
    resources :attendances do
      member do
        post :send_invite
        post :decline_invite
      end
    end
  end
  
  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do 
    resources :users, only: [:index, :show, :edit] do
    match '/users/sign_up', to: 'registrations#new', via: :post
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: "creator_id"
  has_many :attendances
  has_many :attendees, 
    through: :attendances, 
    class_name: "User", 
    foreign_key: "attendee_id"
  belongs_to :location
  accepts_nested_attributes_for :location

  accepts_nested_attributes_for :attendances, reject_if: proc { |attr| attr["user_id"].blank? }
  accepts_nested_attributes_for :attendees

  # after_save :create_reminder_jobs
  # after_save is part of ActiveRecord
  # after_create will only be called once you save sth .. guides.rubyonr.org
  # if (something changed)

  # def create_reminder_jobs
  #   @event = Event.new
  #   alert_time = @event.start_time - @event.attendances.first.trip_duration - 10.minutes
  #   TimeQueryWorker.perform_at(alert_time, id)
  # end

  # def address_compact
  #   [address, city, postcode].compact.join(", ")
  # end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events 
  # GET /events.json
  def index
    # @events = current_user.events
    @events = current_user.attendances.where("accepted IS TRUE").map(&:event).compact
    @user_id = current_user.id 
    @pending_attendances = current_user.attendances.where("accepted IS NULL")
  end


  # GET /events/1
  # GET /events/1.json
  def show
    @event = current_user.events.find(params[:id])
    
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.build_location
    # 5.times do
    @event.attendances.build
    @event.build_creator
  end

  # GET /events/1/edit
  def edit

  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.new(event_params)
    #location??? @event.location_id
    @event.creator = current_user

    respond_to do |format|
      if @event.save
        attendance = @event.attendances.create!(params[:event][:attendances_attributes]["0"].merge( { accepted: true, attendee: current_user, creator: current_user})
          )
        if params[:attendances][:attendee_id].present?
          pending_attendance = @event.attendances.create!(
            creator_id: @event.creator_id,
            attendee_id: params[:attendances][:attendee_id]
            )

          flash[:notice] = "Invite sent"
        end

        format.html { redirect_to [@user, @event], notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :start_time, :date, :time, :creator, :attendances["attendee_id"], :attendances["creator_id"], {location_attributes:[:address, :city, :postcode, :latitude, :longitude]}, {attendances_attributes:[:transport_mode, :attendee_id, :creator_id, :name, :starting_location_id, :accepted]})
    end
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :start_time
    = f.datetime_select :start_time
    %br
  = f.fields_for :location do |loc|
    .field
      = loc.label :address
      = loc.text_field :address
    .field
      = loc.label :city
      = loc.text_field :city
    .field
      = loc.label :postcode
      = loc.text_field :postcode
  %br
  
  - if !@event.id
    = f.fields_for :attendances do |atten|
      = atten.select :transport_mode, {       |
        "Driving"            => "DRIVING",    |
        "Walking"            => "WALKING",    |
        "Bike"               => "BICYCLING",  |
        "Public Transport"   => "TRANSIT"},   |
        selected: "Public Transport"          |
      %br
      .field
        = atten.collection_select(:starting_location_id, current_user.locations, :id, :location_label, {prompt: "Leaving from?", selected: ""})
    %br

  
    = fields_for :attendances do |inv|
      .invite_field
        = inv.collection_select(:attendee_id, current_user.friends, :id, :name, {prompt: "Invite a friend", selected: ""})

  %br
  .actions
    = f.submit 'Save'


    

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
- if !@pending_attendances.any?
  %h2 You have no event invites
- else
  %h2 Event Invites
  %table
    %thead
      %tr
        %th What?
        %th Where?
        %th What time?
        %th With?
        %th
    %tbody
    - @pending_attendances.each do |attendance|
      %tr
        %td= attendance.event.name
        %td= attendance.event.location.address
        %td= attendance.event.start_time
        %td= User.find(attendance.event.creator_id).name
        %td= link_to "Accept", edit_event_attendance_path(attendance.event.id, attendance.id), class: "btn btn-primary"
        %td= link_to "Out", decline_invite_event_attendance_path(attendance.event.id, attendance.id), method: :post, class: "btn btn-primary"


- if !@events.any?
  %h1 No upcoming events
  = link_to 'Add an Event', new_event_path, class: "btn btn-warning"

- else  
  %h2 Upcoming Events
  %table
    %tbody
      %tr
        %th What?
        %th Where?
        %th When?
        %th With?
        %th
        %th
        %th
        - @events.each do |event|
          %tr
            %td= event.name
            / %td= Location.find(event.location_id).address
            %td= event.location.address
            %td= event.start_time
            %td= User.find(event.creator_id).name
            %td= link_to 'Show', event, class: "btn btn-primary"
            %td= link_to 'Edit', edit_event_path(event), class: "btn btn-primary"
            %td= link_to 'Attendance', edit_event_attendance_path(event.id, event.attendances.where(attendee_id: current_user.id).first.id), class: "btn btn-primary"
            %td= link_to 'Delete', event, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-primary"

%br

app/views/events/new.html.haml
%h1 New event
%br
= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%h2= @event.name
%p
  %b Date:
  = @event.start_time
  = "Starting in #{distance_of_time_in_words(Time.now, @event.start_time)})"
%p
  %b Address:
  = @event.location.address
%p
  %b City:
  = @event.location.city
%p
  %b Postcode:
  = @event.location.postcode
%p
  %b Travel Mode:
  = @event.attendances.first.transport_mode
%p

:javascript
  $(document).ready(function(){
    LocationManager.start.lat = #{@event.attendances.first.starting_location.latitude};
    LocationManager.start.lng = #{@event.attendances.first.starting_location.longitude};
    LocationManager.end.lat = #{@event.location.latitude};
    LocationManager.end.lng = #{@event.location.longitude};
    LocationManager.transport_mode = "#{@event.attendances.where(attendee_id: current_user.id).first.try(:transport_mode)}";
    LocationManager.calcRoute();
  });

#trip_length


= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path