config/routes.rb
BonTime::Application.routes.draw do
  root "homes#index"

  resources :messages, only: [:new, :create]

  resources :friendships, only: [:create] do
    member do
      post :accept_invitation
      post :decline_invitation
      post :revoke
    end
  end

  resources :locations

  resources :events do
    match '/events/new', to: 'events#create', via: :post
    resources :attendances do
      member do
        post :send_invite
        post :decline_invite
      end
    end
  end
  
  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do 
    resources :users, only: [:index, :show, :edit] do
    match '/users/sign_up', to: 'registrations#new', via: :post
    end
  end

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  belongs_to :attendee, class_name: "User"
  belongs_to :event
  belongs_to :starting_location, class_name: "Location"


  validates_presence_of :attendee, :starting_location_id
  
  # //:attendee_id -> might be a column entry w/o an attendee


end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
    @event = Event.find(params[:event_id])
    @attendance = @event.attendances.find(params[:id])
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @event = Event.find(params[:event_id])
    @attendance = @event.attendances.build attendance_params

    respond_to do |format|
      if @attendances.save

        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attendance }
      else
        format.html { render action: 'new' }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    @event = Event.find(params[:event_id])
    @attendance = @event.attendances.find(params[:id])
    @attendance.accepted = true
    
    #method for ajax request
    binding.pry
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to event_path(@event), notice: 'Attendance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end


  def decline_invite
    @event = Event.find(params[:event_id])
    @attendance = @event.attendances.find(params[:id])
    @attendance.accepted = false
    @attendance.save!
    # No need to save the event to the user's events here
    # because the user has declined the event.
    redirect_to :back
  end

  # def send_invite
  #   if user_signed_in?
  #     puts params[:attendances]
  #     flash[:notice] = params[:attendances]

  #     # @user = User.find(params[:id])
  #     # Attendance.create!(host_id: current_user.id, friend: @user)
  #     # flash[:notice] = "Invite sent"
  #   else 
  #     redirect_to new_user_session_path, notice: "You need to sign in or sign up before continuing."
  #   end
  # end

  # DELETE /attendances/1
  def destroy
    @attendance.destroy
    redirect_to event_path, notice: 'No longer attending'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_params
      params.require(:attendance).permit(:attendee, :attendee_id, :starting_location_id, :event_id, :transport_mode, :trip_duration, :creator_id, :accepted)
    end
end

app/views/attendances/_form.html.haml
= form_for(@attendance, url: event_attendance_path(@event, @attendance)) do |f|
  - if @attendance.errors.any?
    #error_explanation
      %h2 #{pluralize(@attendance.errors.count, "error")} prohibited this attendance from being saved:
      %ul
        - @attendance.errors.full_messages.each do |msg|
          %li= msg

  .field        
    = f.select :transport_mode, {       |
      "Driving"            => "DRIVING",    |
      "Walking"            => "WALKING",    |
      "Bike"               => "BICYCLING",  |
      "Public Transport"   => "TRANSIT"},   |
      selected: "Public Transport"          |

  .field
    = f.collection_select(:starting_location_id, current_user.locations, :id, :location_label, {prompt: "Leaving from?", selected: ""}, id: "startingLocation")

  = f.hidden_field(:trip_duration, id: "trip_duration") 

  .actions
    = f.submit 'Save', disabled: true, id: "submit"

:javascript
  $(document).ready(function(){
    $("#startingLocation").change(function() {
      var id = this.value; 
      var loc = $.grep(LocationManager.locations, function(l) { 
        return l.id == id;
      })[0];
      LocationManager.start.lat = loc.lat;
      LocationManager.start.lng = loc.long;
      LocationManager.calcRoute();
    });
    LocationManager.locations = #{current_user.json_locations};
    LocationManager.start.lat = #{@event.attendances.first.starting_location.latitude};
    LocationManager.start.lng = #{@event.attendances.first.starting_location.longitude};
    LocationManager.event.lat = #{@event.location.latitude};
    LocationManager.event.lng = #{@event.location.longitude};
    LocationManager.transport_mode = "#{@event.attendances.where(attendee_id: current_user.id).first.try(:transport_mode)}";
    LocationManager.calcRoute();
  });

app/views/attendances/edit.html.haml
%h1 Editing attendance

= render 'form'

= link_to 'Show', event_path(@event)

= # link_to 'Back', event_attendances_path

app/views/attendances/index.html.haml
%h1 Listing attendances

%table
  %tr
    %th User
    %th Event
    %th Location
    %th
    %th
    %th

  - @attendances.each do |attendance|
    %tr
      %td= attendance.user
      %td= attendance.event
      %td= attendance.location
      %td= link_to 'Show', attendance
      %td= link_to 'Edit', edit_attendance_path(attendance)
      %td= link_to 'Destroy', attendance, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Attendance', new_attendance_path

app/views/attendances/new.html.haml
%h1 New attendance

= render 'form'

= link_to 'Back', attendances_path

app/views/attendances/show.html.haml
%p#notice= notice

%p
  %b User:
  = @attendance.user
%p
  %b Event:
  = @attendance.event
%p
  %b Location:
  = @attendance.location

= link_to 'Edit', edit_attendance_path(@attendance)
\|
= link_to 'Back', attendances_path