config/routes.rb
BonTime::Application.routes.draw do
  root "homes#index"

  resources :messages, only: [:new, :create]

  resources :friendships, only: [:create] do
    member do
      post :accept_invitation
      post :decline_invitation
      post :revoke
    end
  end

  resources :locations

  resources :events do
    match '/events/new', to: 'events#create', via: :post
    resources :attendances do
      member do
        post :send_invite
        post :decline_invite
      end
    end
  end
  
  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do 
    resources :users, only: [:index, :show, :edit] do
    match '/users/sign_up', to: 'registrations#new', via: :post
    end
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title b.on time
    %script{src: "https://maps.googleapis.com/maps/api/js?key=AIzaSyDMaMqcnvUj0HnoMe51p7-LxNNAcwc_7XQ&sensor=false", type: "text/javascript"}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %link{href: "http://fonts.googleapis.com/css?family=Pacifico", rel: "stylesheet", type: "text/css"}
    %link{href: "http://fonts.googleapis.com/css?family=Lato", rel:'stylesheet', type:'text/css'}
  %body

    %header
      %nav{id: "top-nav", class: "navbar navbar-default", role: "navigation"}
        .container-fluid
          .navbar-header
            %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to 'b.on time', root_path, class: 'navbar-brand'

          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav
              - if user_signed_in?
                %li
                  = link_to 'Events', events_path
                %li
                  = link_to 'Users', users_path
                %li
                  = link_to 'Profile', user_path(current_user)

            %ul.nav.navbar-nav.navbar-right
              - if user_signed_in?
                %li
                  = link_to 'Add an Event', new_event_path, class: "btn btn-warning"
                %li.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                    = current_user.first_name
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to 'Change Password', edit_user_registration_path
                    %li
                      = link_to 'Logout', destroy_user_session_path, method: 'delete'
              - else
                %li
                  = link_to 'Login', new_user_session_path
                %li
                  = link_to 'Sign Up', new_user_registration_path

      - if alert
        .jumbotron
          .container
            %p= alert
      - elsif notice
        .jumbotron
          .container
            %p= notice
      - elsif "#{params[:controller]}" == "homes"
        .jumbotron
          .container
            %p This app has been deployed in Alpha... More features will be added soon!

    %main{id: "#{params[:controller]}", class: "#{params[:action]}"}
      = yield

    %footer